# Generated by Django 4.0.1 on 2022-01-09 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='quantity',
            field=models.CharField(default='', max_length=100),
        ),
    ]
